"""
WDPO Strong Model Trainer.

Standard DPO training on pseudo-labeled D̂ (generated by DPORewardLabeler).
Uses TRL's DPOTrainer unchanged — the key difference from baseline is
that the training data is D̂ (weak-labeled) instead of D_l (human-labeled).

Hyperparameters (per WDPO spec, Bảng 8):
    learning_rate:               5e-6
    beta:                        0.5
    num_train_epochs:            up to 5
    per_device_train_batch_size: 4 (with gradient_accumulation_steps=4 → effective 16)
    weight_decay:                0.05
    optimizer:                   paged_adamw_32bit
    warmup_steps:                100
    gradient_checkpointing:      True
    lora_r:                      8, lora_alpha: 16
"""

from __future__ import annotations

import logging
from typing import Dict, List

import datasets as hf_datasets
from omegaconf import DictConfig
from trl import DPOConfig

from .sft_trainer import _detect_precision

logger = logging.getLogger(__name__)


class WDPODataset:
    """
    Wraps WDPO pseudo-labeled samples for DPOTrainer.

    trl >= 1.0's DPOTrainer performs its own tokenization from raw text.
    This class is now just a lightweight container — call `.to_hf()` or
    `to_hf_dataset()` before passing to DPOTrainer.
    """

    def __init__(
        self,
        samples: List[Dict],
        tokenizer=None,           # kept for API compatibility; no longer used
        max_length: int = 512,
        max_prompt_length: int = 256,
    ) -> None:
        # Store only raw text fields; trl handles tokenization
        self._data = [
            {"prompt": s["prompt"], "chosen": s["chosen"], "rejected": s["rejected"]}
            for s in samples
        ]

    def __len__(self) -> int:
        return len(self._data)

    def __getitem__(self, idx: int) -> Dict:
        return self._data[idx]

    def to_hf(self) -> hf_datasets.Dataset:
        """Return as a HuggingFace Dataset ready for DPOTrainer."""
        return hf_datasets.Dataset.from_list(self._data)


def build_wdpo_training_args(cfg: DictConfig) -> DPOConfig:
    """
    Build DPOConfig for WDPO strong model training from config.

    WDPO spec (Bảng 8):
      - learning_rate: 5e-6
      - beta:          0.5
      - epochs:        up to 5
      - batch_size:    4 per device, gradient_accumulation=4 (→ effective 16)
      - weight_decay:  0.05
      - optimizer:     paged_adamw_32bit
      - warmup_steps:  100
      - lora_r:        8, lora_alpha: 16
    """
    train_cfg = cfg.training
    use_device_map = cfg.get("device_map", None) == "auto" or cfg.get("use_lora", False)
    fp16, bf16 = _detect_precision(cfg)

    return DPOConfig(
        output_dir=train_cfg.get("output_dir", "outputs/wdpo"),
        num_train_epochs=train_cfg.get("num_train_epochs", 1),
        per_device_train_batch_size=train_cfg.get("per_device_train_batch_size", 4),
        per_device_eval_batch_size=train_cfg.get("per_device_eval_batch_size", 4),
        gradient_accumulation_steps=train_cfg.get("gradient_accumulation_steps", 4),
        learning_rate=float(train_cfg.get("learning_rate", 5e-6)),  # 5e-6 per spec
        lr_scheduler_type=train_cfg.get("lr_scheduler_type", "cosine"),
        warmup_ratio=train_cfg.get("warmup_ratio", 0.1),
        warmup_steps=train_cfg.get("warmup_steps", 0),  # 100 per spec; overrides warmup_ratio when > 0
        weight_decay=train_cfg.get("weight_decay", 0.05),  # 0.05 per spec
        optim=train_cfg.get("optim", "paged_adamw_32bit"),  # paged adamw 32bit per spec
        logging_steps=train_cfg.get("logging_steps", 10),
        save_steps=train_cfg.get("save_steps", 200),
        eval_steps=train_cfg.get("eval_steps", 200),
        fp16=fp16,
        bf16=bf16,
        beta=float(train_cfg.get("beta", 0.5)),           # 0.5 per spec
        max_grad_norm=train_cfg.get("max_grad_norm", 1.0),
        # gradient_checkpointing: required for 7B+ models to avoid OOM
        gradient_checkpointing=train_cfg.get("gradient_checkpointing", True),  # True per spec
        remove_unused_columns=False,
        ddp_find_unused_parameters=False if use_device_map else None,
        report_to="wandb" if cfg.get("use_wandb", True) else "none",
        run_name=cfg.get("wandb_run_name", None),
    )
